### ISSUE TITLE
Validator fails to check for Tumour type

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#1075]
**Describe the bug**
Tumour type has N/A value - this should have been flagged by the validator. The only values allowed are:

Pre-malignant
Primary
Recurrent
Refractory
Metastatic
Not Specified

**To Reproduce**
1. Go to https://www.cancermodels.org/data/models/CMP/SIDM00951
2.  See error

**Expected behavior**

The Tumour type should be Not Specified

**Screenshots**

![Screenshot 2023-03-06 at 16.02.28.png](https://images.zenhubusercontent.com/5b631938e115f66327ad7ac6/040df582-075c-442b-8809-37e86220734b)

**Comment by Mandloi2309** [comment]
Validator couldn't join the patient_sample with the model_validation table as it is empty for cell models and was failing without errors. It is fixed now. 
Also, 'not specified' values have been replaced with not collected or not provided values.

**Comment by zperova** [comment]
@Mandloi2309 the link still shows NA for these values

**Comment by Mandloi2309** [comment]
@zperova It needed a fix on the ETL and Mauricio already worked on it  (https://app.zenhub.com/workspaces/pdcmfinder-board-5f0f036188f27e0014a7bdfc/issues/gh/pdcmfinder/pdcm-etl/239). These changes are on dev right now, so with release on Prod it should get reflected

**Comment by zperova** [comment]
@Mandloi2309 looks like the release in prod did not solve this - the link still shows NA for these values and there are other models with N/A as a value for this and other fields: https://www.cancermodels.org/data/models/GCCRI/ES-6 for example 
Also in this example above, there is a Not specified and Not Collected values. Please resolve this. thank you.

**Comment by Mandloi2309** [comment]
The 'not specified' are coming from ETL as in the data there are no 'Not specified' values. N/A values are fixed in the sheets. There might be a few instances such as when the `SAMPLE TYPE`  is a patient tumour then the `ENGRAFTED TUMOUR PASSAGE` will have a N/A value.
